const products =[
    {
        _id:'1',
        name:'Airpods wireless Bluetooth Headphones',
        description:'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listining experience Built-in microphone allows you to take calls while working',
        image:'./images/airpods.jpg',
        brand:'Apple',
        category:'Electronics',
        price:89.00,
        countInstock:3,
        rating:4.5,
        numReviews:4,
       
    },
    {
        _id:'2',
        name:'IPhone 11 pro 256GB Memory',
        image:'./images/Iphone11.jpg',
        description:'Introducing the 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        brand:'Apple',
        category:'Electronics',
        price:599.00,
        countInstock:10,
        rating:4.0,
        numReviews:4,
    },
    {
        _id:'3',
        name:'Cannon EOS 80D DSLR Camera',
        image:'./images/camera.jpg',
        description:'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and and intuitive design',
        brand:'Cannon',
        category:'Electronics',
        price:929.99,
        countInstock:5,
        rating:3,
        numReviews:3,
    },
    {
        _id:'4',
        name:'sony Playstation 4 Pro White Version',
        image:'./images/playstation.jpg',
        description:'The ultimate home entertainment center starts with Playstation, Whether you are into gaming, HD movies, television, music',
        brand:'Sony',
        category:'Electronics',
        price:399.00,
        countInstock:10,
        rating:5,
        numReviews:3,
    },
    {
        _id:'5',
        name:'Logitech G-series Gaming Mouse',
        image:'./images/keyboard.jpg',
        description:'',
        brand:'Logitech',
        category:'Electronics',
        price:49.99,
        countInstock:7,
        rating:3.5,
        numReviews:2,
    },
    {
        _id:'6',
        name:'Amazon Echo Dot 3rd Generation',
        image:'./images/alexa.jpg',
        description:'',
        brand:'Logitech',
        category:'Electronics',
        price:49.99,
        countInstock:7,
        rating:3.5,
        numReviews:2,
    },
    
]

export default products;